[project]
name = "py-pg-embed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "platformdirs>=4.3.6",
]

[tool.uv]
package = true

[project.scripts]
run-with-pg-dj-database-url = "py_pg_embed:run_with_dj_database_url"
